import pandas as pd
import numpy as np

match_best = pd.read_csv('./SVM_DATA/match_best.csv')
match_second = pd.read_csv('./SVM_DATA/match_second.csv')
match_third = pd.read_csv('./SVM_DATA/match_third.csv')
raw_data = pd.read_csv('./SVM_DATA/raw_data.csv')
training_data = pd.read_csv('./SVM_DATA/Train_valid.csv')
testing_data = pd.read_csv('./SVM_DATA/Test.csv')
similar01_best = pd.read_csv('./SVM_DATA/similar01_best.csv')
similar01_second = pd.read_csv('./SVM_DATA/similar01_second.csv')
similar01_third = pd.read_csv('./SVM_DATA/similar01_third.csv')
similar02_best = pd.read_csv('./SVM_DATA/similar02_best.csv')
similar02_second = pd.read_csv('./SVM_DATA/similar02_second.csv')
similar02_third = pd.read_csv('./SVM_DATA/similar02_third.csv')
non_match_best = pd.read_csv('./SVM_DATA/non_match_best.csv')
non_match_second = pd.read_csv('./SVM_DATA/non_match_second.csv')
non_match_third = pd.read_csv('./SVM_DATA/non_match_third.csv')

match_best.drop(match_best.columns[[1, 2, 3]], inplace=True, axis=1)
match_second.drop(match_second.columns[[1, 2, 3]], inplace=True, axis=1)
match_third.drop(match_third.columns[[1, 2, 3]], inplace=True, axis=1)
raw_data.drop(raw_data.columns[[1, 2, 3]], inplace=True, axis=1)
training_data.drop(training_data.columns[[1, 2, 3]], inplace=True, axis=1)
testing_data.drop(testing_data.columns[[1, 2, 3]], inplace=True, axis=1)
similar01_best.drop(similar01_best.columns[[1, 2, 3]], inplace=True, axis=1)
similar01_second.drop(similar01_second.columns[[1, 2, 3]], inplace=True, axis=1)
similar01_third.drop(similar01_third.columns[[1, 2, 3]], inplace=True, axis = 1)
similar02_best.drop(similar02_best.columns[[1, 2, 3]], inplace=True, axis=1)
similar02_second.drop(similar02_second.columns[[1, 2, 3]], inplace=True, axis=1)
similar02_third.drop(similar02_third.columns[[1, 2, 3]], inplace=True, axis = 1)
non_match_best.drop(non_match_best.columns[[1, 2, 3]], inplace=True, axis=1)
non_match_second.drop(non_match_second.columns[[1, 2, 3]], inplace=True, axis=1)
non_match_third.drop(non_match_third.columns[[1, 2, 3]], inplace=True, axis=1)

match_best.to_csv('./MODEL_DATA/match_best.csv', encoding='utf-8', index = False, header=False)
match_second.to_csv('./MODEL_DATA/match_second.csv', encoding='utf-8', index=False, header=False)
match_third.to_csv('./MODEL_DATA/match_third.csv', encoding='utf-8', index=False, header=False)
raw_data.to_csv('./MODEL_DATA/raw_data.csv', encoding='utf-8', index=False, header=False)
training_data.to_csv('./MODEL_DATA/training_data.csv', encoding='utf-8', index=False, header=False)
testing_data.to_csv('./MODEL_DATA/testing_data.csv', encoding='utf-8', index=False, header=False)
similar01_best.to_csv('./MODEL_DATA/similar01_best.csv', encoding='utf-8', index = False, header=False)
similar01_second.to_csv('./MODEL_DATA/similar01_second.csv', encoding='utf-8', index = False, header=False)
similar01_third.to_csv('./MODEL_DATA/similar01_third.csv', encoding='utf-8', index = False, header=False)

similar02_best.to_csv('./MODEL_DATA/similar02_best.csv', encoding='utf-8', index = False, header=False)
similar02_second.to_csv('./MODEL_DATA/similar02_second.csv', encoding='utf-8', index = False, header=False)
similar02_third.to_csv('./MODEL_DATA/similar02_third.csv', encoding='utf-8', index = False, header=False)

non_match_best.to_csv('./MODEL_DATA/non_match_best.csv', encoding='utf-8', index = False, header=False)
non_match_second.to_csv('./MODEL_DATA/non_match_second.csv', encoding='utf-8', index=False, header=False)
non_match_third.to_csv('./MODEL_DATA/non_match_third.csv', encoding='utf-8', index=False, header=False)


